//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad.AreasCalc.CalculadoraServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculadoraServiceReference.AreasWebServiceSoap")]
    public interface AreasWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        decimal AreaCuadrado(decimal Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(decimal Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        decimal AreaCirculo(decimal Radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCirculoAsync(decimal Radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo2", ReplyAction="*")]
        decimal AreaCirculo2(decimal Diametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo2", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCirculo2Async(decimal Diametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        decimal AreaTriangulo(decimal Base, decimal Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(decimal Base, decimal Altura);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreasWebServiceSoapChannel : Actividad.AreasCalc.CalculadoraServiceReference.AreasWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreasWebServiceSoapClient : System.ServiceModel.ClientBase<Actividad.AreasCalc.CalculadoraServiceReference.AreasWebServiceSoap>, Actividad.AreasCalc.CalculadoraServiceReference.AreasWebServiceSoap {
        
        public AreasWebServiceSoapClient() {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal AreaCuadrado(decimal Lado) {
            return base.Channel.AreaCuadrado(Lado);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(decimal Lado) {
            return base.Channel.AreaCuadradoAsync(Lado);
        }
        
        public decimal AreaCirculo(decimal Radio) {
            return base.Channel.AreaCirculo(Radio);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCirculoAsync(decimal Radio) {
            return base.Channel.AreaCirculoAsync(Radio);
        }
        
        public decimal AreaCirculo2(decimal Diametro) {
            return base.Channel.AreaCirculo2(Diametro);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCirculo2Async(decimal Diametro) {
            return base.Channel.AreaCirculo2Async(Diametro);
        }
        
        public decimal AreaTriangulo(decimal Base, decimal Altura) {
            return base.Channel.AreaTriangulo(Base, Altura);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(decimal Base, decimal Altura) {
            return base.Channel.AreaTrianguloAsync(Base, Altura);
        }
    }
}
